language:
  - python
python:
  - "2.7"
install:
  - cd backend
  - python setup.py dev
script:
  - py.test --tb=native
notifications:
  irc:
    - "irc.freenode.org#pyfidelity"
  email:
    - mail@pyfidelity.com
